name: Lastarria
version: '${project.version}'
main: fr.kangpvp.lastarria.Main
api-version: 1.19
authors: [ KangPvP ]
description: Serveur Survie
commands:
  boutique:

  titre:

  unclaim:

  claim:

  opkangpvp:

  opnotvape:

  lastacoin:

  lastaitem:

  rtp:

  fly:

  sethomesss:

  sethome:

  succes:

  spawn:

  tuto:



  hdv:

  menu:

  metiers:
